export const STORAGE_SERVICE = "STORAGE_SERVICE";
export const STORAGE_MODULE_OPTIONS = "STORAGE_MODULE_OPTIONS";

export const STORAGE_PROVIDER = "STORAGE_PROVIDER";
export const STORAGE_PROVIDER_MODULE_OPTIONS = "STORAGE_PROVIDER_MODULE_OPTIONS";

// 15 mins
export const STORAGE_DEFAULT_SIGNED_URL_EXPIRES = 900000;
