name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node: [14, 15]
    name: Test Node v${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: anchan828/save-to-file@master
        with:
          text: ${{ secrets.GCP_SA_KEY }}
          file: "~/credentials.json"
          encoding: "base64"
      - name: Set NEST_STORAGE_GCS_KEY env
        run: echo "NEST_STORAGE_GCS_KEY=$HOME/credentials.json" >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node
      - name: Install npm packages
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Test monorepo packages
        if: github.repository != 'anchan828/nest-lerna-template'
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          NEST_STORAGE_S3_KEY: ${{ secrets.NEST_STORAGE_S3_KEY }}
          NEST_STORAGE_S3_SECRET_KEY: ${{ secrets.NEST_STORAGE_S3_SECRET_KEY }}
        with:
          coverageCommand: npm test
          debug: true
