name: CI

on: [push]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Set up docker-compose
        run: docker-compose up -d
      - uses: anchan828/save-to-file@master
        with:
          text: ${{ secrets.GCP_SA_KEY }}
          file: "~/credentials.json"
          encoding: "base64"
      - name: Set NEST_STORAGE_GCS_KEY env
        run: echo "NEST_STORAGE_GCS_KEY=$HOME/credentials.json" >> $GITHUB_ENV
      - name: Install npm packages
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test monorepo packages
        run: npm test
        env:
          NEST_STORAGE_S3_KEY: ${{ secrets.NEST_STORAGE_S3_KEY }}
          NEST_STORAGE_S3_SECRET_KEY: ${{ secrets.NEST_STORAGE_S3_SECRET_KEY }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
